// <auto-generated />
using System;
using Gemelo.Components.Cts.Database.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gemelo.Components.Cts.Database.Migrations
{
    [DbContext(typeof(CtsDatabaseContext))]
    [Migration("20210312172926_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gemelo.Components.Cts.Database.Models.CtsUser", b =>
                {
                    b.Property<int>("CtsUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailsAsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rfid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CtsUserID");

                    b.ToTable("CtsUsers");
                });

            modelBuilder.Entity("Gemelo.Components.Cts.Database.Models.StationConfiguration", b =>
                {
                    b.Property<int>("StationConfigurationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DetailsAsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationConfigurationID");

                    b.ToTable("StationConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
